happyInsurance/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls',namespace="main"))
]

main/urls.py
from django.urls import path

from main import views
                             
app_name = "main"  

urlpatterns = [
    path('login',views.user_login, name="user_login"),
    path('logout',views.user_logout, name="user_logout"),
    path('signup',views.user_signup, name="user_signup"),
    path('index',views.index, name="index"),
    path('profile', views.profile, name="profile"),
    path('quote', views.quote, name="quote"),
    path('myPlan', views.myPlan, name="myPlan"),
    path('purchase', views.purchase, name="purchase"),
    path('purchaseFinal', views.purchaseFinal, name="purchaseFinal")
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>HappyInsurance - Here for all your healthcare needs</title>

  <!-- css -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" />
  <link rel="stylesheet" type="text/css" href="{% static 'plugins/cubeportfolio/css/cubeportfolio.min.css' %}">
  <link href="{% static 'css/nivo-lightbox.css' %}" rel="stylesheet" />
  <link href="{% static 'css/nivo-lightbox-theme/default/default.css' %}" rel="stylesheet" type="text/css" />
  <link href="{% static 'css/owl.carousel.css' %}" rel="stylesheet" media="screen" />
  <link href="{% static 'css/owl.theme.css' %}" rel="stylesheet" media="screen" />
  <link href="{% static 'css/animate.css' %}" rel="stylesheet" />
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <script src="{% static 'js/jquery.min.js' %}"></script>

  <!-- boxed bg -->
  <link id="bodybg" href="{% static 'bodybg/bg1.css' %}" rel="stylesheet" type="text/css" />
  <!-- template skin -->
  <link id="t-colors" href="{% static 'color/default.css' %}" rel="stylesheet">

  <!-- =======================================================
    Theme Name: Medicio
    Theme URL: https://bootstrapmade.com/medicio-free-bootstrap-theme/
    Author: BootstrapMade
    Author URL: https://bootstrapmade.com
  ======================================================= -->
</head>

<body id="page-top" data-spy="scroll" data-target=".navbar-custom">


  <div id="wrapper">

    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
      <div class="top-area">
        <div class="container">
          <div class="row">
            <div class="col-sm-6 col-md-6">
              <p class="bold text-left">Monday - Saturday, 8am to 10pm </p>
            </div>
            <div class="col-sm-6 col-md-6">
              <p class="bold text-right">Call us now +1 XXX XX XXX</p>
            </div>
          </div>
        </div>
      </div>

      <div class="container navigation">
        <div class="navbar-header page-scroll">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
          <a href="{% url 'main:index' %}"><h2 class="h-ultra" style="margin-top: 20px;">Happy<span style="color:#5f9ea0;">Insurance</span></h2></a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
          <ul class="nav navbar-nav">
            {% if user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Welcome {{user}} <b class="caret"></b>  <i class="fa fa-user fa-2x circled bg-skin"></i></a>
                    <ul class="dropdown-menu">
                    <li><a href="{% url 'main:myPlan' %}">My Plans</a></li>
                    <li><a href="{% url 'main:user_logout' %}">Logout</a></li>
                    </ul>
                </li>
            {% else %}
                <li class="active"><a href="#intro">Home</a></li>
                <li><a href="#service">Services</a></li>
                <!-- <li><a href="#doctor">Doctors</a></li>-->
                <li><a href="#testimonial">Testimonials</a></li> 
                <li><a href="#pricing">Pricing</a></li>
                <li><a href="{% url 'main:user_signup' %}">Sign-Up Now</a></li>
            
            {% endif %}
           
            
            
          </ul>
        </div>
        <!-- /.navbar-collapse -->
      </div>
      <!-- /.container -->
    </nav>
    <section id="main-content">
    {% block content %} {% endblock %}
</section>

<footer>

    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-md-4">
          <div class="wow fadeInDown" data-wow-delay="0.1s">
            <div class="widget">
              <h5>About HappyInsurance</h5>
              <p>
                Lorem ipsum dolor sit amet, ne nam purto nihil impetus, an facilisi accommodare sea
              </p>
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-md-4">
          <div class="wow fadeInDown" data-wow-delay="0.1s">
            <div class="widget">
              <h5>Contact Us</h5>
              <p>
                For more information, please reach out to us.
              </p>
              <ul>
                <li>
                  <span class="fa-stack fa-lg">
                                  <i class="fa fa-circle fa-stack-2x"></i>
                                  <i class="fa fa-calendar-o fa-stack-1x fa-inverse"></i>
                              </span> Monday - Saturday, 8am to 10pm
                </li>
                <li>
                  <span class="fa-stack fa-lg">
                                  <i class="fa fa-circle fa-stack-2x"></i>
                                  <i class="fa fa-phone fa-stack-1x fa-inverse"></i>
                              </span> +1 XXX XX XXX
                </li>
                <li>
                  <span class="fa-stack fa-lg">
                                  <i class="fa fa-circle fa-stack-2x"></i>
                                  <i class="fa fa-envelope-o fa-stack-1x fa-inverse"></i>
                              </span> hello@happyinsurance.com
                </li>

              </ul>
            </div>
          </div>
        </div>
        <div class="col-sm-6 col-md-4">
          <div class="wow fadeInDown" data-wow-delay="0.1s">
            <div class="widget">
              <h5>Follow us</h5>
              <ul class="company-social">
                <li class="social-facebook"><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li class="social-twitter"><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li class="social-google"><a href="#"><i class="fa fa-google-plus"></i></a></li>
                <li class="social-vimeo"><a href="#"><i class="fa fa-vimeo-square"></i></a></li>
                <li class="social-dribble"><a href="#"><i class="fa fa-dribbble"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="sub-footer">
      <div class="container">
        <div class="row">
          <div class="col-sm-6 col-md-6 col-lg-6">
            <div class="wow fadeInLeft" data-wow-delay="0.1s">
              <div class="text-left">
                <p>&copy;Copyright - Medicio Theme. All rights reserved.</p>
              </div>
            </div>
          </div>
          <div class="col-sm-6 col-md-6 col-lg-6">
            <div class="wow fadeInRight" data-wow-delay="0.1s">
              <div class="text-right">
                <div class="credits">
                  <!--
                    All the links in the footer should remain intact. 
                    You can delete the links only if you purchased the pro version.
                    Licensing information: https://bootstrapmade.com/license/
                    Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Medicio
                  -->
                  Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>

</div>
<a href="#" class="scrollup"><i class="fa fa-angle-up active"></i></a>

<!-- Core JavaScript Files -->
<script src="https://kit.fontawesome.com/51dca21af8.js" crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.min.js' %}"></script>
<script src="{% static 'js/wow.min.js' %}"></script>
<script src="{% static 'js/jquery.scrollTo.js' %}"></script>
<script src="{% static 'js/jquery.appear.js' %}"></script>
<script src="{% static 'js/stellar.js' %}"></script>
<script src="{% static 'plugins/cubeportfolio/js/jquery.cubeportfolio.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/nivo-lightbox.min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>

</body>

</html>

templates/login.html
<div>
  <div >
    <h1>Please Login</h1>

      <form method="post" action="">
        {% csrf_token %}
        {# A more "HTML" way of creating the login form#}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Username">

        <label for="password">Password:</label>
        <input type="password" name="password">

        <input type="submit" name="" value="Login">

      </form>
      <a href='/reset-password'>Forgot Password</a>

  </div>
</div>

templates/myPlan.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <br>
    <br>
    <section id="pricing" class="home-section bg-gray paddingbot-60">
        <table class="table table-advance table-hover" style="padding: 2%; margin: auto; width: 80%;">
            <thead>
              <tr>
                <th></th>
                <th></th>
              </tr>
            </thead>
            <tbody id = "main">
                <tr>
                    <td> Plan Purchased</td>
                    <td> {{purchase.package_id.package_type}}</td>
                </tr>
                <tr>
                    <td> Total Cost</td>
                    <td> ${{purchase.premium_amount}}</td>
                </tr>
                <tr>
                    <td> Purchase Date</td>
                    <td> {{purchase.date}}</td>
                </tr>
                <tr>
                    <td> Services Accessible</td>
                    <td>
                        <ul>
                            {% for service in services %}
                            <li> {{service.service_name}}</li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
                <tr>
                    <td> Hospitals Accessible</td>
                    <td>
                        <ul>
                            {% for hospital in hospitals %}
                            <li> {{hospital.hospital_name}}</li>
                            {% endfor %}
                        </ul>
                    </td>
                </tr>
            </tbody>
            </table>
    </section>

{% endblock %}

templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <br>
    <br>
    <section id="pricing" class="home-section bg-gray paddingbot-60">
        <div class="container marginbot-50">
          <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
              <div class="wow lightSpeedIn" data-wow-delay="0.1s">
                <div class="section-heading text-center">
                  <h2 class="h-bold">Health packages</h2>
                  <p>Take charge of your health today with our specially designed health packages</p>
                </div>
              </div>
              <div class="divider-short"></div>
            </div>
          </div>
        </div>
  
        <div class="container">

          <div class="row">
          {% for key,value in data.items %}
          {% if key.package_type == 'Basic' %}
            <div class="col-sm-4 pricing-box featured-price">
              <div class="wow bounceInUp" data-wow-delay="0.1s">
                <div class="pricing-content featured">
                  <h2>{{key.package_type}} Package</h2>
                  <h3>${{key.base_amt}}<span>/ per month</span></h3>
                  {% for v in value %}
                  <ul>
                    <li>{{v}} <i class="fa fa-check icon-success"></i></li>
                    <!-- <li>Post Examination Review <i class="fa fa-check icon-success"></i></li>
                    <li>General Screening – Basic <i class="fa fa-check icon-success"></i></li>
                    <li><del>Health Screening Report</del> <i class="fa fa-times icon-danger"></i></li> -->
                  </ul>
                  {% endfor %}
                  <div class="price-bottom">
                    <a href="{% url 'main:quote' %}?package={{key.package_type}}" class="btn btn-skin btn-lg">Purchase</a>
                  </div>
                </div>
              </div>
            </div>
           
            {% elif key.package_type == 'Platinum' %}
            <div class="col-sm-4 pricing-box featured-price">
              <div class="wow bounceInUp" data-wow-delay="0.3s">
                <div class="pricing-content featured">
                  <h2>{{key.package_type}} Package</h2>
                  <h3>${{package.2.base_amt}} <span>/ per month</span></h3>
                  {% for v in value %}
                  <ul>
                    <li>{{v}} <i class="fa fa-check icon-success"></i></li> 
                    <!-- <li>General Screening – Basic <i class="fa fa-check icon-success"></i></li>
                    <li>Body Composition Analysis <i class="fa fa-check icon-success"></i></li>
                    <li>GR Assessment & Scoring <i class="fa fa-check icon-success"></i></li> -->
                  </ul>
                  {% endfor %}
                  <ul>
                      <li>All Premium Services <i class="fa fa-check icon-success"></i></li>
                  </ul>
                  <div class="price-bottom">
                    <a href="{% url 'main:quote' %}?package={{key.package_type}}" class="btn btn-skin btn-lg">Purchase</a>
                  </div>
                </div>
              </div>
            </div>
  
           {% else %}
            <div class="col-sm-4 pricing-box general">
              <div class="wow bounceInUp" data-wow-delay="0.2s">
                <div class="pricing-content general last">
                  <h2>{{key.package_type}} Package</h2>
                  <h3>${{package.1.base_amt}}<span>/ per month</span></h3>
                  {% for v in value %}
                  <ul>
                    <li>{{v}} <i class="fa fa-check icon-success"></i></li>
                    <!-- <li>General Screening – Regular <i class="fa fa-check icon-success"></i></li>
                    <li><del>Health Screening Report</del> <i class="fa fa-times icon-danger"></i></li> -->
                  </ul>
                  {% endfor %}
                  <ul>
                      <li>All Basic Services <i class="fa fa-check icon-success"></i></li>
                  </ul>
                  <div class="price-bottom">
                    <a href="{% url 'main:quote' %}?package={{key.package_type}}" class="btn btn-skin btn-lg">Purchase</a>
                  </div>
                </div>
              </div>
            </div>
  
            {% endif %}
            {% endfor %}
          </div>
  
        </div>
      </section>

{% endblock %}
  

templates/purchaseFinal.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<style>
.buttonNew {
    display: block;
    width: 250px;
    height: 40px;
    background: #4E9CAF;
    padding: 10px;
    text-align: center;
    border-radius: 5px;
    color: white;
    font-weight: bold;
}
</style>

    <section id="testimonial" class="home-section paddingbot-60 parallax" data-stellar-background-ratio="0.5">
        <div id="regForm" class="container regForm">
            <div class="panel-heading">
                <h3 style="text-align: center;">Congrats on buying the {{package}} insurance !!!</h3>
            </div>
            <!-- <div class="row">
                <div class="col-lg-9">
                    <p>Base Amount : </p>
                    <br>
                    <p>Additional Costs : </p>
                    <br>
                    <p>Taxes : </p>
                    <hr>
                    <p>Total : </p>
                </div>
                <div class="col-lg-3">
                    <p> ${{base_price}} </p>
                    <br>
                    <p> ${{additional_costs}}</p>
                    <br>
                    <p> ${{tax}} </p>
                    <hr>
                    <p> ${{total}} </p>
                </div>
            </div> -->
            <br>
            <div class="row">
                <div class="col-lg-offset-4">
                    <a class="buttonNew" href="{% url 'main:index' %}" >Return to Home Page</a>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-lg-offset-4">
                    <a class="buttonNew" href="{% url 'main:myPlan' %}" >See Purchase Details</a>
                </div>
            </div>
        </div>
    </section>
    
{% endblock %}

templates/purchaseForm.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <section id="testimonial" class="home-section paddingbot-60 parallax" data-stellar-background-ratio="0.5">
        <div id="regForm" class="container regForm">
            <div class="panel-heading">
                <h3 style="text-align: center;">Final Pricing</h3>
            </div>
            <div class="row">
                <div class="col-lg-9">
                    <p>Base Amount : </p>
                    <br>
                    <p>Additional Costs : </p>
                    <br>
                    <p>Taxes : </p>
                    <hr>
                    <p>Total : </p>
                </div>
                <div class="col-lg-3">
                    <p> $100 </p>
                    <br>
                    <p> $25</p>
                    <br>
                    <p> $5 </p>
                    <hr>
                    <p> $130 </p>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col-lg-offset-5">
                    <input type="button" value="Buy Now" class="btn btn-skin" style="width : 20% ; font-family:'Roboto', sans-serif;">
                </div>
            </div>
        </div>
    </section>
    
{% endblock %}

templates/signup.html
<div>
    <div >
      <h1>Please Signup</h1>

        <form method="post" action="">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">

          <label for="password">Password:</label>
          <input type="password" name="password">

          {{form.as_p}}

          <input type="submit" name="" value="Signup">

        </form>
        <a href='/reset-password'>Forgot Password</a>

    </div>
  </div>